import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'

export default function Home() {
  const [text, setText] = useState(['First Text']);
  const textRef: any = useRef('');
  const handleText = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (text[0] === 'First Text') setText(['']);
    setText((inData) => [...inData, textRef.current.value]);
  }

  useEffect(() => {
    textRef.current.value = ('');
  }, [text]);

  const clearFnc = () => {
    setText(['First Text']);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Input App</h2>
        <form action="" onSubmit={handleText}>
          <label htmlFor="text">
            <p>Enter text</p>
            <input type="text" id='text' ref={textRef} />
            <br />
          </label>
        </form>
        <button onClick={clearFnc}>Clear</button>
        <hr style={{margin:'10px 0'}} />
        <h3>Texts entered</h3>
        {text.map((data, index) => (
          <p key={index}>{data}</p>
        ))}
      </div>
    </>
  )
}
